"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
first = 1
second = 2 
final_list = list()
final_list.append(first)
final_list.append(second)
answer =0
answer += second
while True:
	third = first + second
	if third % 2 == 0:
		answer += third
	final_list.append(third)
	if third  >= 4000000:
		break
	first, second = second, third
	
print(final_list, f"\n the answer is {answer}", )
	
		